### ISSUE TITLE
Run it on main thread

### ISSUE THREAD

**Issue by xeoneux** [ryohey/wavelet#10]
Hi @ryohey 
I'm playing a midi file in the following manner:

As soon as I'm getting events from a midi keyboard stream, I'm simply sending 
```js
postSynthMessage({ type: "midi", midi: noteData, delayTime: 0 })
```
However, if there are a lot of events, it's causing problems with the output. It kind of hangs.

Is there a way to run this on the main thread so that there's no postMessage to the worker?

**Comment by ryohey** [comment]
@xeoneux Since that problem does not occur with signal, which uses wavelets, there may be a problem with the SoundFont you are using or code other than wavelet. Can you provide the code to reproduce it?

**Comment by xeoneux** [comment]
Ah, solved it, I wasn't sending the note off events, so they were all still playing in the worklet and that caused the issue 😅

Is there a way I can send `postMessage` data in bulk? Because a lot of times a lot of notes play at once. Also, would it cause any substantial performance improvement?

**Comment by ryohey** [comment]
There is some overhead, but since each event is very lightweight and the wavelet does not process it immediately, but waits until the next call to AudioWorklet's process, so I don't think it will be a big problem. If there are any latency or other issues, please let me know. You can use Chrome's inspector to see how long it takes for an event to be processed.

**Comment by xeoneux** [comment]
Thanks @ryohey all the events are processed under 50ms so the latency isn't that high. But there's surely some as compared to my previous approach which was using `soundfont-player` on the main thread.
